/**
 * Generates mastra/component-reference.generated.ts — the LLM-facing
 * component reference — from the real catalog Zod definitions.
 *
 * Needed because the custom kit exports definitions and React components from
 * the same modules; importing them from the (server-side) agent instructions
 * would drag React client code into Next's RSC graph. Run after changing the
 * catalog:  bun scripts/gen-component-docs.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { shadcnComponentDefinitions } from "@/lib/jr/components/shadcn/catalog";
import { z } from "zod";
import { customComponentDefinitions } from "../lib/jr/components/custom/catalog";

interface ComponentDef {
  props: z.ZodType;
  description?: string;
  events?: string[];
  slots?: string[];
  example?: unknown;
}

const merged = {
  ...shadcnComponentDefinitions,
  ...customComponentDefinitions,
} as unknown as Record<string, ComponentDef>;

const reference = Object.entries(merged)
  .map(([name, def]) => {
    const jsonSchema = z.toJSONSchema(def.props, {
      unrepresentable: "any",
    }) as { properties?: Record<string, unknown>; [k: string]: unknown };
    delete jsonSchema.$schema;
    const lines = [
      `### ${name}`,
      def.description ?? "",
      `props: ${JSON.stringify(jsonSchema.properties ?? {})}`,
    ];
    if (def.events?.length) lines.push(`events: ${def.events.join(", ")}`);
    if (def.slots?.length) lines.push(`slots: ${def.slots.join(", ")}`);
    if (def.example !== undefined)
      lines.push(`example props: ${JSON.stringify(def.example)}`);
    return lines.filter(Boolean).join("\n");
  })
  .join("\n\n");

const out = `// AUTO-GENERATED by scripts/gen-component-docs.ts — do not edit.
// Regenerate after catalog changes:  bun scripts/gen-component-docs.ts

export const COMPONENT_REFERENCE = ${JSON.stringify(reference)};
`;

const target = path.join(
  import.meta.dirname,
  "..",
  "mastra",
  "component-reference.generated.ts",
);
writeFileSync(target, out);
console.log(
  `wrote ${target} (${Object.keys(merged).length} components, ${reference.length} chars)`,
);
